### ISSUE TITLE
The website is only in English

### ISSUE THREAD

**Issue by AlbinCauderlier** [particl/particl.io#13]
Would you use a crypto-currency if you don't understand the website?
More translation -> More users

[List of languages by number of native speakers - Wikipedia](https://en.wikipedia.org/wiki/List_of_languages_by_number_of_native_speakers)

**Comment by DrDBanner** [comment]
Thanks for the heads up. This is already addressed and on the todo list.

**Comment by AllienWorks** [comment]
Website already available in English, French and German; more languages coming as soon as somebody will translate. Cheers!
