### ISSUE TITLE
Particl Core Windows Exe link broken

### ISSUE THREAD

**Issue by SquibblyDee** [particl/particl.io#131]
**Description**
The link associated with the Particl Core (Qt) Windows executable redirects to a 404 page.

**Before**
https://github.com/particl/particl-core/releases/download/v0.19.2.13/particl-0.19.2.13-win64-setup-unsigned.exe

**After**
https://github.com/particl/particl-core/releases/download/v0.19.2.13/particl-0.19.2.13-win64-setup.exe

**Evidence**
![image](https://user-images.githubusercontent.com/18860841/133000629-fde6fb9b-0bb9-495f-a1a3-5e81e04dd75e.png)
![image](https://user-images.githubusercontent.com/18860841/133000622-433dff93-3a13-4b7d-94f6-95ded7e7773b.png)

**Comment by AllienWorks** [comment]
Thanks for the find. Link just fixed!
