### ISSUE TITLE
Slider needs adjustment 

### ISSUE THREAD

**Issue by SativaL** [particl/particl.io#31]
This is how the slider page looks for me:

https://i.imgur.com/sTem7FW.png

**Comment by LiteBit** [comment]
What browser is that in please?

**Comment by LiteBit** [comment]
I get full screen bleed
![image](https://user-images.githubusercontent.com/6236019/36998309-74b99570-208a-11e8-847e-1999e93dc424.png)

thats chrome on win10

**Comment by AllienWorks** [comment]
Already fixed this. The "screen cuts the text" issue will happen everytime. It's a carousel which is focused on the middle items..
