### ISSUE TITLE
Animated decentralized Network header

### ISSUE THREAD

**Issue by SativaL** [particl/particl.io#33]
https://www.shutterstock.com/de/video/clip-20299471-stock-footage-abstract-technology-background-growing-network-connections-chaotic-particles-and-lines.html?src=rel/32080279:9

we definitely need something like this as the main header (with white and greenish particl branding colours) and then we could talk about the slogan that is between the animation.

maybe we could ask hypercube to make a header for us (where when each triangle of the decentralized network zooms in, there is a small picture shown of utility from the project).

like this small logos or so https://pbs.twimg.com/media/DVnSxPNVMAAeMfs.jpg:large

but just the network animation effect in particl branding style would be very good, looks more professional and up to date and not so static then.

i wish i could show you how this effect looks in my head :smile: its pretty decent, colors are like white matt and particl green
normal speed moving (mid) just a view triangles with lines (not like 20), more like only a bunch.. interacting with each other
then in the middle or so a 70% transparent white field
that maybe says for example
"whatever slogan you guys choose"

**Comment by AllienWorks** [comment]
The header is good as it is, let's stay original. I would like to animate the header in the future though.

What you're describing is used by a big chunk of crypto projects. Also keep in mind that every dynamic element (videos even more) adds a lot of bandwidth to the website and/or requirements for CPU etc. As the site is responsive and aimed globally, it's a nice idea to keep it simple. Not eveybody has a high speed optical internet connection.
