### ISSUE TITLE
The dashboard is gone and with it evidence of our swap

### ISSUE THREAD

**Issue by nunyab86** [particl/particl.io#36]
As above, kind of important to have access to the dashboard to have evidence for our swap.

**Comment by AllienWorks** [comment]
The dashboard is not gone, only the link disappeared – you can still visit it at: https://portal.particl.io/login. But thanks for pointing this out.

**Comment by LiteBit** [comment]
Maybe this could be added to Particl.Wiki and/or Reddit sidebar for archive sake.

**Comment by AllienWorks** [comment]
^ Indeed. I plan to add the link to website's footer as well.

**Comment by nunyab86** [comment]
Thanks all for the quick solution!
