### ISSUE TITLE
Reduce the number of cards in Why Particl

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl.io#40]
![selection_010](https://user-images.githubusercontent.com/27031337/37051751-51eaee48-2145-11e8-8312-4fe47a4d5dc6.png)

We should reduce the number of cards in the Why Particl section. People tend to skip sections where there is too much information, so we should probably keep it short and sweet and focus on the most important of them. 

Right now, there's 12 cards, let's make it 6 or 9. I would propose we keep these: 
- Secure
- Private By Design
- Decentralized
- Currency-Agnostic
- Scalable
- Passive Income

I propose we let go of these: 
- Open-Source
- Protocol-Agnostic
- Privacy Smart-Contracts
- Mobility
- Academic Review
- Community Governance

**Alternatively**

We could choose to keep 9 cards. In that case, I would propose to keep these: 
- Secure
- Private By Design
- Decentralized
- Currency-Agnostic
- Scalable
- Passive Income
- Community Governance
- Academic Review
- Protocol-Agnostic

And let these go: 
- Open-Source
- Mobility
- Privacy Smart-Contracts

**What do you guys think?**

**Comment by AllienWorks** [comment]
I'm honestly against this. The text is there for those who are interested in Particl and want to know more. Yes, there are many other channels with info available, but the website should have a nice overview of all features/reasons "why Particl".
