### ISSUE TITLE
Atomic Swap Card Touch Up

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl.io#43]
1- Change "Crypto Agnosticism" for "Currency Agnosticism"
2- Change "Atomic Swaps" for "Almost Any Cryptocurrency Accepted". The reasoning behind this is that it is more noob-friendly. Complete newcomers may not know out of the bat what is Atomic Swaps, but they understand when we saw almost any currency can be integrated. 
3- Change the text to the following: 
"In the spirit of connecting the many different crypto communities together, the Particl platform is designed in such a way that it can easily integrate with almost any cryptocurrency using decentralized atomic swaps and third-party integrations. As the Particl platform requires its native PART coin to function and keep its users' activities private, all incoming currency transactions are automatically converted into PART."

Original version is this: 
"In the spirit of connecting many different crypto communities together, the Particl platform is designed in such a way that it can accept almost any currency using atomic swaps and third-party integrations. However, as the platform (marketplace, extended messaging, future Dapps, etc) requires PART to function in a private way (CT and RingCT), all incoming currency transactions are automatically converted into PART."
![selection_015](https://user-images.githubusercontent.com/27031337/37060215-9f3a0414-215d-11e8-9f5f-f03c72989dea.png)

**Comment by AllienWorks** [comment]
OK, but shouldn't the text read:

> In the spirit of connecting ~the~ many different crypto communities together, the Particl platform is designed in such a way that it can easily integrate ~with~ almost any cryptocurrency using decentralized atomic swaps and third-party integrations. As the Particl platform requires its native PART coin to function and keep its users' activities private, all incoming currency transactions are automatically converted into PART.

?

Can we get an input from some native English speaker? @LiteBit

**Comment by bb2k16** [comment]
2) "Almost Any Cryptocurrency Accepted". sounds incomplete. how about "Accept Major Cryptocurrency" or just simply "Cryptocurrency Accepted" to avoid the mouthful, and go on the explain in details, rather than in an attempt to capture everything in the header.

**Comment by AllienWorks** [comment]
@bb2k16 "Cryptocurrency accepted" sounds too broad/general to me.

I don't mind the more tech-y title ("Atomic Swaps") as it clearly describes the feature. I would offer a more newbie-friendly description though (what @cryptoguard suggested).

**Comment by AllienWorks** [comment]
Change coins to:

- BTC, LTC, DCR, VIA, VTC
- ETH, ETC, SALT, DAI, BAT

**Comment by AllienWorks** [comment]
Updated the illustration to go more with the website's general style:

![atomic-swaps_mono svg](https://user-images.githubusercontent.com/1965795/37107716-68f21a6c-2235-11e8-8877-09cba56d341e.png)

The text is still open for discussion.

**Comment by SativaL** [comment]
Why DAI and SALT and BAT ?

Why not major coins (expect ripple and other crap coins like btrash)

Bitcoin, litecoin ..

**Comment by cryptoguard** [comment]
Because they are ERC-20 token. As far as I know, altcoin.io only accepts Bitcoin and ERC-20 tokens right now.

**Comment by PhilipM83** [comment]
Hey guys, I tried to write a simpler version of the Atomic Swaps card, let me know what you think:
___
Atomic Swaps
**All Currencies Welcome**
The Particl platform accepts a wide range of cryptocurrencies and provides maximum privacy at the same time. All incoming currency transactions are automatically converted into Particl’s native currency, PART. This way, you can use your favorite cryptocurrency while being protected by PART’s powerful privacy features.
___
Thoughts: 
- Tried to keep it simple & short
- clearly communicate the benefits (e.g. “...accepts a wide range of cryptocurrencies and provides maximum privacy at the same time”)
- speak directly to the user (e.g. “use your favorite cryptocurrency”) 
- I think that "However, as the platform requires PART to function [...]" (taken from the original) sounds a bit negative to me, tried to frame that in a positive way. 

___
_[Alt. – Slightly longer, a bit more tech-y]_
Atomic Swaps
**All Currencies Welcome**
The Particl platform is designed to accept a wide range of cryptocurrencies while providing maximum privacy. Particl seamlessly exchanges currencies across blockchains through decentralized atomic swaps and third-party integrations. All incoming currency transactions are automatically converted into Particl’s native currency, PART. This way, you can use your preferred cryptocurrency while being protected by PART’s powerful privacy features.
___

**Comment by AllienWorks** [comment]
So do we have a final text? So far I propose the combination of most of the suggestions to this:

> Cryptocurrency Agnosticism
> ### Atomic Swaps
> In the spirit of connecting many different crypto communities together, the Particl platform is designed in such a way that it can easily integrate almost any cryptocurrency using decentralized atomic swaps and third-party integrations. As the Particl platform requires its native PART coin to function and keep its users' activities private, all incoming currency transactions are automatically converted into PART.

Feedback?

**Comment by AllienWorks** [comment]
@LiteBit @cryptoguard @bb2k16 – can we decide on the final text please? I propose the one from the previous comment. Your opinions?

**Comment by LiteBit** [comment]
like text for atomic swaps on #48
