### ISSUE TITLE
Switch Social Banner With Particl Desktop Banner

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl.io#46]
I think the Particl Desktop should come before the social media banner, having the social media banner first feels counter-intuitive. I propose we switch places between them as people will usually want to read the website first before joining a community's chat channels. 

![selection_018](https://user-images.githubusercontent.com/27031337/37080081-fadb1fec-21b2-11e8-8f43-cc50f9aad02d.png)
![selection_019](https://user-images.githubusercontent.com/27031337/37080082-faef50fc-21b2-11e8-860c-78860bf9eb7b.png)

**Comment by AllienWorks** [comment]
I understand your point, but I don't think this is needed.

- Social links are in the footer as well
- Download link is in the header and under the intro illustration

Moreover the way the site is currently built is that the Download section is part of the "footer" template ~ the bottom part which is repeated on each page.
