### ISSUE TITLE
Add a "more details" link that links to a dedicated Wiki page for the front page cards

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl.io#47]
Add a link to each of the frontpage's cards that links to more in-depth section of that card's topic. 

For example, if we were to add the Particl Marketplace card (https://github.com/particl/particl.io/issues/44), we could have it linked to the www.particl.wiki/marketplace (or in that example in particular, could link to marketplace.particl.io) page to allow people looking for more details to find it without having to look too much. 
![selection_014](https://user-images.githubusercontent.com/27031337/37246814-87a73fbe-247e-11e8-9f8d-eea2991f92eb.png)

**Comment by AllienWorks** [comment]
Could you please list all the "read more" links for each of the cards? I'm not even sure if we have a wiki page for each of these..

**Comment by cryptoguard** [comment]
I have made one for the marketplace, but could do one for each if we decide to go with this: www.particl.wiki/marketplace

**Comment by AllienWorks** [comment]
Yep, let's do this ^

**Comment by LiteBit** [comment]
agree
