### ISSUE TITLE
HP Copy Suggestions

### ISSUE THREAD

**Issue by PhilipM83** [particl/particl.io#48]
Hey guys, as per a quick hello on Reddit (https://www.reddit.com/r/Particl/comments/82l0y2/is_particl_a_decentralized_marketplace_or_dapp/dvda9yr/), I had a look at the copy for the Atomic Swaps card, Marketplace card and the homepage headline. You’ll find a couple options below, let me know what you think. 

**ATOMIC SWAPS CARD**
Thoughts:
- Tried to keep it simple & short
- Clearly communicate the benefits (e.g. “...accepts a wide range of cryptocurrencies and provides maximum privacy at the same time”)
- Speak directly to the user (e.g. “use your favorite cryptocurrency”)
- I think that "However, as the platform requires PART to function [...]" (taken from the original) sounds a bit negative to me, tried to frame that in a positive way.
___
Atomic Swaps
**All Currencies Welcome**
The Particl platform accepts a wide range of cryptocurrencies and provides maximum privacy at the same time. By using atomic swaps and third-party integrations, all incoming currency transactions are automatically converted into Particl’s native currency PART. This way, you can use your favorite cryptocurrency while being protected by PART’s powerful privacy features.

_[Alt. – Slightly longer, a bit more tech-y]_
The Particl platform is designed to accept a wide range of cryptocurrencies while providing maximum privacy. Particl seamlessly exchanges currencies across blockchains using atomic swaps and third-party integrations. All incoming currency transactions are automatically converted into Particl’s native currency, PART. This way, you can use your preferred cryptocurrency while being protected by PART’s powerful privacy features.
___

**MARKETPLACE CARD**
Thoughts:
- Clearly describing what the marketplace is (e.g. “The Particl marketplace is an anonymous, secure and decentralized e-commerce platform running on the blockchain.”)
- Describing benefits instead of just the technology (e.g. “Profit from a low-cost, highly scalable platform, buy and sell without any middlemen or central authorities [...]”) 
- Using active verbs that speak directly to the user (e.g. “settle transactions in confidentiality [...] leave no personal data behind”)
___
Confidential commerce
**The Particl Marketplace** 
The Particl marketplace is an anonymous, secure and decentralized e-commerce platform running on the blockchain. It offers a comprehensive suite of built-in privacy features and is secured and governed exclusively by its community. Profit from a low-cost, highly scalable platform, buy and sell without any middlemen or central authorities, and earn passive income by receiving fees generated by the marketplace.

_[Alt – shorter]_
Experience a completely anonymous, secure and decentralized marketplace running on the blockchain: Buy, sell and trade without any central authority, settle transactions in confidentiality, communicate through encrypted chats and leave no personal data behind. On a low-cost, highly scalable e-commerce platform that’s designed to work with any cryptocurrency.

_[Alt – more focus on marketplace being the first dapp and specific privacy features]_
The Particl marketplace is the first decentralized application (dApp) built on the Particl framework. The marketplace is a low-cost, secure and highly scalable peer-to-peer e-commerce platform designed with powerful privacy features at its core: private transactions, encrypted data, secure messaging, IP address anonymization, metadata stripping, private listings and more. It runs autonomously on the blockchain and is designed to work with almost every cryptocurrency, making it easily accessible for everyone.
___
**HEADLINES (OPTIONS)**

Thoughts:
I think “The World’s Most Private Marketplace” is already pretty great, it’s simple, punchy and to the point. The only thing that’s maybe lacking is the bigger picture of Particl being more than just a marketplace. Three alternative options:

- The Privacy Platform for a Decentralized Economy
- We’re Building a New Economy. 
Privacy-focused. Democratic. Decentralized.
- The Particl Platform. 
Trade with Maximum Privacy.

**Comment by cryptoguard** [comment]
I like these: 

**Atomic Swaps**
The Particl platform accepts a wide range of cryptocurrencies and provides maximum privacy at the same time. By using atomic swaps and third-party integrations, all incoming currency transactions are automatically converted into PART, Particl’s native currency. This way, you can use your favorite cryptocurrency while being protected by PART’s powerful privacy features.

**Marketplace**
The Particl marketplace is the first decentralized application (dApp) built on the Particl framework and is entirely governed by the Particl community. It is a low-cost, secure and highly scalable peer-to-peer e-commerce platform designed with powerful privacy features at its core: private transactions, encrypted data, secure messaging, IP address anonymization, metadata stripping, private listings and more. It runs autonomously on the blockchain and is designed to work with almost every cryptocurrency, making it easily accessible for everyone.

@AllienWorks 
@LiteBit 

Thoughts?

**Comment by AllienWorks** [comment]
**Atomic Swaps**
This ^ one is also nice, however I can't make up my mind between that and this one: https://github.com/particl/particl.io/issues/43#issuecomment-375620317

**Marketplace**
For the marketplace, I like https://github.com/particl/particl.io/issues/44#issuecomment-372700190 more tbh.

**Comment by AllienWorks** [comment]
@LiteBit @cryptoguard @PhilipM83 So what do you guys think? Can we agree on some version?

**Comment by LiteBit** [comment]
Agree with the Atomic Swaps one and the Marketplace #44 one.
