### ISSUE TITLE
Display Messes Up When Put On Half-Screen Mode

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl.io#54]
Whenever putting the browser in half-screen mode, some stuff will be badly displayed. Examples below: 

![1](https://user-images.githubusercontent.com/27031337/39208653-9cb6dace-47d1-11e8-89a0-e15ac6db325d.jpg)
![2](https://user-images.githubusercontent.com/27031337/39208654-9cca7548-47d1-11e8-90b5-9223376f0746.jpg)

**Comment by AllienWorks** [comment]
Yes, I'm aware of this. This will need some more time, so I'm postponing this after MP alpha.

**Comment by cryptoguard** [comment]
This has been fixed afaik, cannot replicate the issue anymore.

**Comment by AllienWorks** [comment]
Fixed with latest PR :)
