### ISSUE TITLE
Slider is bugged: lots of whitespace before numbers where you can slide forward/backwards show up

### ISSUE THREAD

**Issue by kasprrr** [particl/particl.io#63]
win 10 Chrome:

![1](https://user-images.githubusercontent.com/37086658/44120298-317fbac2-9fd9-11e8-8918-9d4336c468b6.png)

![2](https://user-images.githubusercontent.com/37086658/44120300-33cee4ec-9fd9-11e8-8ee4-6ac4fe721c3e.png)

**Comment by AllienWorks** [comment]
Can't reproduce. Are you sure it's not caused by any of your browser plug-ins/extensions?

**Comment by kasprrr** [comment]
Pretty sure, no other website is giving me problems like this. I don't have any plugins/extensions installed other than adblock plus, trezor and some google docs related things. Working from a Microsoft Surface Book.

**Comment by AllienWorks** [comment]
I asked other team members to try it, nobody with Win/Chrome had this issue. Putting this on hold as you might be the only one. If anybody else has the same problem or more info, please speak up :)

**Comment by kasprrr** [comment]
It may have something to do with the language bar, when i change english to german, it looks like this:
![111](https://user-images.githubusercontent.com/37086658/44507584-5654ae80-a668-11e8-9a88-1cc66b615246.png)
![222](https://user-images.githubusercontent.com/37086658/44507592-5b196280-a668-11e8-86f9-39ddad0b2537.png)

**Comment by kasprrr** [comment]
fixed! issue can be closed : - )
