### ISSUE TITLE
Test builds on Downloads page

### ISSUE THREAD

**Issue by LiteBit** [particl/particl.io#70]
Would it make sense to have a section on this page https://particl.io/downloads/ that lets people download testing versions of builds?

Or a rolling list of current testing builds that link to GitHub pull request or pre-release tag?

most Fiona builds use transfer.sh which limits downloads to 10 day availability. 
some type of automation might be necessary on both ends to ensure testers have builds available consistently.

**Comment by AllienWorks** [comment]
Fixed.
