### ISSUE TITLE
Discord link on homepage is expired

### ISSUE THREAD

**Issue by CryptoBeans** [particl/particl.io#79]
A user has reported that the Discord link at the bottom of the homepage is expired. The blog post that talks about migrating to discord uses this link instead: https://discordapp.com/invite/YFeXbFZ

**Comment by cryptoguard** [comment]
@AllienWorks 

Let's use this link: https://discord.me/particl

Customized and easy to remember

**Comment by AllienWorks** [comment]
Fixed, thanks for notice :)
