### ISSUE TITLE
Remove Google+ social media from footer

### ISSUE THREAD

**Issue by amazzoccone** [particl/particl.io#81]
Google + was shutdown 🤙.

Changes should be done in files:
https://github.com/particl/particl.io/blob/master/_includes/social-icons.html#L68
https://github.com/particl/particl.io/blob/master/_sass/layout/_navigation.scss#L199

I could make the PR if accepted 👍.
Thanks for let us contribute!

**Comment by AllienWorks** [comment]
Google+ link removed already, thanks!
