### ISSUE TITLE
Add an "As Seen On" Section

### ISSUE THREAD

**Issue by cryptoguard** [particl/particl.io#94]
Add an "As seen on" section to the top of the homepage with these names and logos: 

* BitcoinNews (https://bitcoinnews.com/wp-content/uploads/2019/06/bitcoinnews-logo-new-1.png)
* BlockTelegraph (https://launch.quantmre.com/wp-content/uploads/QRE-PRESS-BLOCKTELEGRAPH-LOGO.jpg)
* NextBigFuture (data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAQoAAAC+CAMAAAD6ObEsAAABNVBMVEX///+71lhXueKXszunxTg1nL0nj6dfYGCioaF1mT5Bfqc5a4dlhzqfnp7A2ElRt+WamZn19fV4wcvY2Njn5+dOUFBXWVnq7vKEhYWxv59Db4lcgSpzdHSqqamwr6+Mj4++vb3KyspvlC+3yKF9fX3f5NqIqMHe3t6EnK00eaMqZIJra2vCwsKvusUPcZ+vwdKSrypVr9IGWHsAhaAAkbaduEe0zlqqx0OiwiRggjlGhKlujkTq79/C0ZqUsEdElLKDo0j2+fHS4udMpcKdvwDU3rqSwNS+2eVFkq+hw89EfJdsprh1s8tJmK1MfJhWsNSpyNJYj7LE3OYsYX+fsLydtXx/n1Gvw2/k7M+Prhq4z2anvWDI1aO+0365yonI2pJqi03I1beBoiSZz9TR5uXR3pq8zJFEAqkSAAANX0lEQVR4nO2dC1fbyBXH5foRx0SttJJtSrGwt6TeBjeB5eXEhGBICHkAWbIlkJBmH02//0fovDV3ZmSHJkZjd35nzx7ZupJn/rqvGXF2Pc/hcDgcDofD4XA4HA6Hw+FwOBxfwfDPBv6q82uY90gnTfzLX3TufG/g/Ne8xzphrr5/eEfn/LaB394N8x7tRLnq7w50MQYGJfY2Vz/MdJDslEolgxgGLXaLxdV/5T3cifKpXypt72laaCGyV0Ss7uQ93EkyRFIgMW4/HOMWm0SKD3kPd6J8IlqUNpUoOTc4RbF4eZH3cCfJcJtIUdqGKWNwrjsF4sNMV5FnT0tMDJAyQIjsMiWKl8/yHu5E2SpxirIYklvscadAzLRbXPSFFnLKGBicAmXO/+Q93GszvJuN2il9lLSQugzhFntFiakrqHfh2uL2yOXEzlNJijRlDAxOMYV91tVvo+rB6jto/Ul2i7TLGBicori5OmUF9aJfzK4He8XLx8B6Z7sEYSnD4BSIdxm/aSvv+6XNc3M9QHNTH+3VU0ULmjIGulNMYUElZWHXWA/w3NQQUd2CpIyHRMBNVYri5pQVVFIWtvfuaPWAzk1poZ/1NS1wlzEwOAXS8SqnOf2P7GTVgz1jC/1elwKnjIHBKaavz/rch10TrwebxkcLC2qaMj6YlJi2gjqEKVCrB6vQ/KMhRJBTFbaMWljWZ4UKQ8Vt0/jf3r2j1wO1oJb01FkqFQqFLVOI2FVQ7/4yYJzvMf4JHtZQin/SZZwrTQJ8tJ8NIVIgGMSwa+Pi4vJc65Ch417Ik9u8rdYDtaCawqOQJYZd+1nv+zwj8kK5qcwOxv8uqgegc7yEbnGlZYtCIVOLVav6rJ2+2HrK6CJ3lLXFntIkQOGGW4oS24VCthh29VkfxW71QJRJ6LjqOkuZj/JoQUApSmhiKFk3Z+hDL96WMyJcIAzB3Az1AN7wfV+xVgDX2lVQH4vd6jQjQscF8b+tPdxL2Gdd9LdV62zHsKvPknarRUZcfWyyAI9Z7prgo5UDyqAEFMOujQvRRUkZETqu2M821wPl0Q77Y5SQhbTsBdGWGLuYnjI7YWGuB0pB/Wy0znAMuwqqSPrSEKHjiv3sjIebUVCzlZB+ybKCasiI0HFZn6U9ZmasRDwLqBFOIV18adXGxQ54iGyEwHFpyc2uB7vwhrSgjlGiwAurVW5Bkn46UTK93aFmkf1wla1KUlDHK0GvtesFES6XakaE2zKahTIfJeJRQI0LD+mXrOqzUBelj1Dts0bNZ1XZuBhlrV6srm5zZlvPiIrjbo18zFuX0C0+faFTkGuLdvVZf9QpwY0Lg4XMZ3C/YWGMOeDjjc51DM3vDPx7rIXE7/CGv48xH3Vtvhye/knl9KAJLDQDQPk5uN++fr8RHN7oXEezXy7/QeFg/Uy2aG4cqBYSp5VjeMMD7X7ZHBw3PXt4XS6vweFVKq+AxaFqAa2hbt7zjRHWkLXK+pubnOoYzjbK5fKpPDzEvmyB3EZ3nFQ2RbfmAbzfCCGOK5Vjm/7AF4+8LALgFM9t/dUIC3UylXXo4i8yrQ0qrsMsky/PsVOIAMDDUyfHLPQHTWSrrMO81wT3Gy2Eqnm+hOSRswAgsYEG+CLTQpsMAjrF4YbZ2uBO6JdAIOYMHzly6dNjNjeY1IUFfNBMNjXv7ZfF/bIRv2RTIW2WBfwhK5MLUwvTZCoVeMPXwjo7c4pfqlhWSClHJ4/4+GCXcCiJZZiMkvfONgzWSmyk14JAzBnuzkcLc49qR2yAZyYLPbdSXoFiKPJKZuaU3MlGp3jycm7upFZjbvHKYCGHyJo8GSXvvdGsM2NDyzL5Qt0ZCTG38KhWo24BC+n+BpjcGiugYjZQtxAY6yECrlXb9Vwh7nw0h8FK1GoVtUsADg9yq9HFD6FwSuYE7mRZIUW909FLosQCUYKEiKm7MuRWU95rllWyXUINxHxpkiQxx8MDc5RZSHFKkXIrA97wtSbFWqYQyjInZ87u/ci4d58DH9UL2SlAbjXlPSWvyCGypgmxblN35YX/4DzgwCfVhEJIuZW5OCykulOwzHl6rClhVyEdT5oFUd8xR5yC5lZj3ntuUIKEiB4blnVX4xEOD3OrcAsl7xmV0GsOxaptivEwh+e5dY7nVnPee27IFOjik59MSli1TTEeNjcuBAuPGs+c6jaFUYiXWs0xOpTtHKRJAjhFrUay4Dp08UODEi8X1JpjzjK282YDCJE6BZ2cUkibenjgixdAchFKTJdT4M3al6kQPGeKzKnkPa2Q0gxzkgaUzHQV0jcbshByeJDJKS5+ZhRCqzmM6Sqk3osf396TmPu7zP0j+ObDU1ZtSs1R3WK6CqkX/vyDzN8AD5TJwEJ6pKUX4BZWbVN8a8BS/olItQtpUMlSTFl3dT2kbYonUoaRao7kFspbxdkiTJXIrDlT211dD+EUchui1Zzp7K6uh9g1h9X3pAbgIfI67+FOkgOWJN4CJaBTpG4xXd3V9djfUJOEySn4dvqUdVfXQto1l1lQlaBuMdOFFHVXTxY0JdTwYG4xZdsU1+TwiRYbpvAgbjHTfabnPXhrUMLkFLX7j2baJ1Cu+GFuQePEIMVP6sJlBml+GbMvhMPhcDgcDofD4XA4HA6Hw+FwTAlh0m63O+xDdX4J0orYhm6LfAzS7d24XVVsl3o3P/pvShj4ftBmH5brDZXlmJyZJ2dWuBTxkmbYqLfyGP83JAyqVb/NPsw3bqk06sRllsiZRSZFu64b3mrMuhRoinj+QIqkbjCbSSkWGbeoMPXEg1L0qBKNxuKyzGI76zemBE2Kxjz/jz/HPp3zfAikiKlCjfmu8t+IznEWnDCWCDNOhR48z7/vYikSdoZIsZRevigEkKQIiECN6o3N7xrEqAgIqkksToS9Fv866HgRNgsSeqpDPuDTVQz+0NOlSAxSxNQnFm94kl9GTKfD8IOIfd+tBum3qA70sF1ACkKMz/itWL7OIEWbCDDvyVJQeeqRPg4LIPOqUp8gUL/o+uJr4hWom8Lf+Ohs2KJ22J9GeQVJo/W2J0sxD8qqZRApWgmm6rPny3zF99sdShd9FZKvqqHXJv4ReWGnQ1ylxSxo2hR5kBTNxgq+WyrFCokPn/xypy3TyR7iTRGnRSDEk/RJgU/IUQwsIyJBLyLhwa4w9xUrCFJMGytYxFSKkBw0aMoB3WndgvQhSeGFxN9Dng1ixbRHXQX/K6EuPqbFaixRMyEFLaUNesU8sF2e9ETHA6RoMSnIpBPNtsVTrM+CfVy3uUgXWWYplrlHkO9slSIhJaIjYP7Bq43PK4BBitTl8Yd6gM+kASI32UlAWbJXClEjfKmvoEQ+r63sAq3bDOIuo0WaKaWCLBItpDKD6DaslSLkUoC+ghoQKUTvoUshr7UDIsAKaLHS71KmQQrNK2hvIXqPMVJ0acBEshS9hnAVaGerFKR1oGsLutRgT7HHGlCfT3ikFKzJ7shShKzaym5hsRQeywlaBenSxpR0F+wCshxjp1UpegavYLsVvMrS29orRcgaDF9ZKcTUIRI/TRdhIIULkaIq/g9NUeoAkhQh6Tdv1Zcj0ZZGVkuB1p4kW8bybgLpKoKYpU46fxownW4s1hcrHLYxgZ1M3rqJ2Pf11NLeYkpG3MZaBLyPwGmT9proiHbetN+k2QM1B5F5Q69xS9vQ65k39KyUgh630zU6FcAXS49eeshrim+WorEI1yCEzoppE9QKKRBtehy20DFvqqNWIOihlImhHuORM0skXYTtKjkT4eWVygqzp2dE2QiTxYZma8FyjO7asQ/yMTrDG8du7NFjvvSg38o3QGe6kQI3Z2e68o/qxpOfqsPh+FrS2BVdIPqiE5qPAdw+6xheoO4GheKsHdudUVL1ea0QU0hQjeADb0vHSQAQLzTwB35clY7xxSk+eGHOyw/GhrQZJgHb78b/iBGhhiHg0+9Jx9RaLFzFmgNfzI9RXyqO6a6wz7fUA0mLLvlRtvi1QQrUS/m4dVbej8lSIJMA1Nu4hUSIQekdKQW9e1QFO6Yh3SqzJ0Bwt9kyjCNLCn7WV159j5SC3R9vCIodMXyCbxfbAVp4BaZ3EJOQAjf2IkLwsk7bVM+VnjZNyiSk6FYlr+gGVekeNngHXlsm4h1V+vr4m0pBc0VHWt2zfYBEYEHaxFKkr9IDYwX5ailorSb1QgQj3RIRP2zBG2UsRStpUZKWuZh+rRS0BcFekM6YSNHiVO3wivG5wv8GAdJRSlUEcoUNjJKiKx1/gRTiDzN9sQHkSWkT3UVuNsl7WRuypSBLCvQQedXH7YAPB61LgeVieQA+byEFbqnkphJL07ZJiywpyEZf0g3DuNOSdvgZuhQR2RiMkX1PLplyMY2gH3T5Fbb8XVqWFF7kk3znB4Y/tTBIgf9AC1UKn9pLXaTUV+D+sg2vYOsxKyoIXjiae75YrCl1P24FgZbyIrForfYk+3a6XRr78tqXbZ/aU0y7nU4nyznDboTOpnuUKZ1ez9Cth/hmHWVTIpJ+gJyXT8aR8ncLDofD4XA4HA6Hw+FwOBwOh8Ph+L/lv1JSg8Cz8KZsAAAAAElFTkSuQmCC)
* HackerNoon (https://jobs.hackernoon.com/uploads/tenant/logo/7823/Hacker_Noon_Jobs_copy.png)
* The Merkle (https://themerkle.com/wp-content/uploads/2019/02/The-Merkle.png)
* Business Insider (https://n0lcqtmqb8-flywheel.netdna-ssl.com/wp-content/uploads/2016/01/business-insider-logo.png)
* Yahoo Finance (https://s.yimg.com/uu/api/res/1.2/q7.iGJvnxTydr6xNRrjkvQ--~B/Zmk9c3RyaW07aD00MDA7cHlvZmY9MDtxPTgwO3c9NDAwO3NtPTE7YXBwaWQ9eXRhY2h5b24-/https://media-mbst-pub-ue1.s3.amazonaws.com/creatr-uploaded-images/2019-05/ec0d4dd0-8220-11e9-bf7f-ae1a8925cae3)
* International Business Times (https://static.adweek.com/adweek.com-prod/wp-content/uploads/sites/9/2016/05/Screen-Shot-2016-05-23-at-9.28.15-AM.png OR http://blog.ourcrowd.com/wp-content/uploads/2017/07/IBT.jpg OR https://cdn.vox-cdn.com/thumbor/Dzm9WDkfwbUjzFJBf9mAbDnb81I=/0x0:640x480/1200x800/filters:focal(269x189:371x291)/cdn.vox-cdn.com/uploads/chorus_image/image/63708808/qob3exbt-copy.0.1485859344.0.png)
* TownHallFinance.com (data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAXEAAACICAMAAAAmsyvzAAAA+VBMVEX///+wICUBAQEhSSIAAAAAOgDAwMAzMzMAPACrq6tlZWVJSUkAOACvHSKvGB7BysEIPgr05OXa4NqvERkWQxerAADn6+etAA3EYWQQQBLbrK0TRhVpgWmmsaaImoi2wrb89PW+UFPoxMWyKCzR2NEnJycfTSFacVq0Njqdq50hISHjubrK0MqOjo7j4+NAX0EAMgDx9PHx2dlziHT36uvu0tMAKgA2WDdycnIaGhrW1tY6OjqBgYHGZ2rPiYsALQBYWFi3QUXTj5HIyMjbo6XKd3mhoaF7j3w7XDwAIwC4PUDIcnXEY2XRjpDbpqiNjY1NZ01hd2IAHwBwYVJTAAASHElEQVR4nO2d6ULbuhKADUnAhThkcWLSHsAhrIUCIaEsBVpoWe7pOS3c93+Ya0m2PCONTNoShXA9v6g2W5/k0cxISh0nl1xyySWXXHL5VVntLA4tndq43/YX5OR0Xcr7+dE8YwY8Y/30K8j58h48/Quq9LZZGVqah6N58ZHIXBHIaW8kz3gDn1GcATnzMGMWVdoJpoaWCSM+LaX4flTEp8FDMHGQkRN/NsmJQ8mJ25acuG3JiduWnLhtyYnblhdLXPWAMOOJ9oBeKPGdqw4SDxHHeVeT5OW/WOKKDBqAt+eN5D3tyKQQr+XEf0Fy4lBy4rblFRI/enu52LmKpLN48+MofI4e/JqEq9f8BS6+HRG5JPGzmZNPs5F8OpnJHoOzmfP5WSGf5s9nvtKlbBJfvWgEQSMxG9nfF6tqmcO3UEKQE6Kctzuo2g7I+REa044WkxeInt69Dh1FCOIzszBqPbdn6tzeh+miKl/eEAXtEV/dajawGTnlVZpdTM6pNYNUkC1/CHOCZhfWCrtNkBOKxCtQocls1NpiE7oOXhCoA64R3/sUgUuTIvlAdm5P7GVMQ+Ept1pRW8TD703FUYqLN7+HmB0YleAtyFltonreAOQNQF7lIk7sgAcy4qsN+J7i4d/wW6rEZxSIDOMJ0bs3WjlZfFb9KiwRP9xSeyulsQXZOReAU+MSZHzDoYUA6mE4GsE1TXynqXxhPB1/Ypi485UAWSz+1Hr30wSclz8bB/HDKXKCx1z/DkHRa9CYnK5MvuMxQ/MfjkYzGQpEfHAYEMCnvAZ8Nia+vkeC1BA6HzKAs/It+8TDLOAR8n9AWThdPTgWHdxG4wZUukzfwJuqERWatS36FdBnpBCfpUEWlU3+s0zgUfk5+8Q7RpUS8wDzdQCX1yAlPujiOVrpwAdUiHRIvLJoeAVvKgTtzCEaRt2MVfNpNnD1o7BBXFnzGkEzwFYL6jaamqmxUkONRHW6oE4lbS6d++ijMH5kTWivzD0BL6aBDBBMMBFU/sRcfjTEt3DXb3aOVm+6aM4FwGa4ATlAWWsx+SAdDWiqpFU6GuXICm80lFSknTTiBL8o8RPsHZzikWly8vVr5DEV8TBYJo5YNeIzWgP0mXtTafG3oHjjX5l8raoFYGYgU0UOhEq8Eixef7u+7OCPpbKYQZwRjGRWmbOQ4BkCnljryFzEasUC8UXQc28rSQ0REPBtHwLiwFj5rhIHa96PtApQNgrxYDEeix2s5ODqrBAvrsee+q15zt5CB+kcJMN0yHX0xNFSCMgeoamfftvQB/KkZxn+rRp3YDSAIgILKiYepE9AyL0ucAcwcaA9bo1zdg6SBd1GFaC3P3ri0FZGBsY/aJKn6WjpTBJDbWsVTM4tsHBek+1EpcGTkdnTAJtUiq0CbJJZRBxwAmocRQCQoQmXztETh+oArpBIYUOrBBjXqTtzpJgqrDE5OaEaTz8iRBw5TPAJU4GR+LlD5yDiUHuYpjKy4EdOHAVKcGgK9TslshoQyenwyOakhoKGYzPVEZg4DCX8gGNtJm5a74zEv5oqWCUOcWB3A33cYB2EzUlj5d8k0ZMKXX4wwFTxKmnzkDh+q51hiBeLMBo+YyDeg9HZl0EcLlNIjTvOFXIK03QwEjJZGjyBnKBytQUrBYzEIJ/zCj4YuWRG4tNDEf/580MiP6Ev+mFsxKEd3fiOsqCG90C8G4QPvUac5nnJJJbujqQIygc/0mYQcTTWwxFfx8RN1p5BimMjDlcpHDZCgwHVAVxSmyFPCiXmjiODgEnUBZgqTRDD7Rg+oWGJoz7/KvEP4yMO/R+FOHZG06UN2iUxQskoakKSjPNCEFUBRuY4ifdwxNwucaisA7zlghcwYMZAa0/48lJ5R03IRTRWIcBJRep6XMR7Z+fvlbCAVeJTMPiKia+aiAP/MjZWpFcZzWs5UPEnA5pBH9FYiJ+9+bKuh76sEvcgcbzHhYmDqCnQ/TEqqaojvV4DOp0JWA6Qn2OdeGtm7j0RarRMPESdw8QPEXGw5u3AyBRPSVrxtkLHkbkBzwMrRRMeK7VLvHe7TtJ+wcTBHB9Al4atqIdyWl9AlAJwqoPQLoVV4mfE6YmXThztqgNVxOf+KlLdUunw9gbpSoF2oi0SP5vXaY/NVvmtOY58GlZHepVcUade57+4FRA4tEn8nOBdHJs9/nvEvykUparmobAjtHQCpY/2LK0Rn6N4z40trvJ7WgX4QJxVYqqIk1gyVu6xpRMYNg101sgS8Tl1Sy6Sk7PxRbJ+y1aB+w9e5NQMEq8ytgelV8Vis+nGhhIos0P8jcr7/YcZNd2uPV4x2+NHRq0CaLFdMVkwDoXJEFikRsLUqUXb8raIKzug50lQfXzEvWF9TnSeG6iKyBlNvUyxNEqfJ2pwkD4ABg4dS8TRWdDibLqJMT7if/+Gl4/Ch9GHcQnmNCIWmYOHTUMTdogjSnAPY3zEYb+x9WaMHTpo5yiqJE2VhmBak0vnFtyO66ImrBBvofNBL2Of03g6Ge/yw/h4JGEa8658l99JwjRMbZcw1T/KwmmF+BlKhhXGRxztSNwYs9KjQ0IugAVy6GFTBe7BHaUFlfG0QhxtxhmPF9oljo6rIC8cbVYoWSAg6HV3FFMF+vnfrtKFU7ljYoP4OayALqyMjzjsXeUqhFlbcFHFdgbygb7LGZ2svHIMKp2uLNdQfgHABnFUwXjk1i5xeO51Ct1IGEDDsalM0BrIlOTkLE59J7AJ3cUt2Cf+QuZ4uGXiihygeAc5FbhbJwcsgaMe39ehOuMmPjc24thYMVwl0RZO4iwtOvNMjIdi7I+BOFo5x7eXj++ogcNo6HicYqk7yqnEGFtq/hHj0VQvIVtfOaF1+HN8e/lRLiSbTvJrw0HPWI504vSJcdlEqLRg2zqcNjn/tonjE5fyktUqHAjVeXHY/ThNVRtOg8bPVRdO6x7QdPE0Sb5VIriWieMbPMENm861a3T3SrnIqgGLS6V6o6ZpFcW7cuwQ76GLbsX1mVY0CrfKLRZ8ccjKzSs0WxuNbrfbQKOAz2HGol38QXpDM1bQwQku1iNZPDx+Ok1c1YJN2SCOL96wIgqugPrlDU1xyFOfKk4xHNpKYD9aG+8Aib/GSdwxXV9N+nypV1FcJ42a+gV4gdaAnR2JaWU+J2XWYVProCU7t8S7WbfEA9V1iaWifAngqqF+vVPzf8az6yaLTPdQhT1DhZH9EkLN/NMTU80LogKTC6UO2rM7VL4A3aC3tbM8TyBnJaZhBXB7wtKvfQw61G9tMBRNHVUsqs2NNbVCXI3LONaI996rC2VU4I3iHIFfCHkW4kHFk1Kp0IV+NAJNtXiNZodaNIUcNT0kTZT7dwVnhlr9DijRUIjDmoi46f8VmDH+XwROD/3OEF8836g1gHn4W/+rgSK17hYUU7EfVw32I1XJwLBfqrox846EmZFAsAl56WVkculMpdlT8AdFnFX4wt3hiE+D/29jWjkFd4t/Iiv+Ma1P4D/iKMIt56GIf3KeQ2qrl/90rra63a2rq8Wbt4dhdvFQkczcp6oP9YKtPShDVREy82X+NLLFT+fnT74+9aN9xmegpz/jT/+F4WAwJICJktbe2V7r6WK55JJLLrnkkksuubxGabVao/m17D+X3oJJ1lA5Islp8cQ61Ww9krUM+7dOtae/F1mgvpbZdm/hbr/g+37h+HGJKtUy9tiOvd5yS7Qc/IXKlfUkZ/djlFj2qcnklsvlj0vmx96z9kqueR6usbZLZarAw0G5/PnOUG9h88Bt+wUufvXgQZ8PKx8NPf64YH7fZ5RWwSB+H5V7x5JU4iVWsLpMNLvBMszE62X+DHfFWGKNl2j3iazNCGibemhU677s416UtYIrrqHH7qQQL5SIr/EJ4stt8Yy/jCUE8UKV0Ctm4tspbz/5q7SvvN7LIO5XNSkPTdzf1Jt9gvgxq8Y6aVQrMXGqbRPx3mbMslp+t7/5cFxyOXW/gDWLIN7We/zZInF/c0mTbfz8DOKF8q7WbDZxplTad36WWomJUyVMxDer4m2Ol+p8IHsrm3zOt/dRMU7cXyZ6bGnl5ANOa0UoWcQLx1rxbOJMqbhOmZ7CQhLihWPtMzAQf+TA2wU4RPX7ajTHMUlO3M0wk0Ysz0Lc3VaLZxN/x9t6jMgdmNSKJK4vzDTxZbGMqyvDXVlRKhNPvL3NuajgMokzmlHmUvWJMqJtV/3YSeJihKq6bbOsqrxJJ15aYCpCm4iZxFmNcstpMbXyYCgjRmW7Shg0JPFjrrHNtk8qk068utRifa0qn24mcfZItprdUzM4Fk5822G6uazQoYgv8ClOOmOqTDrxqOoym4iPOCuL+JobP5F/HaZC3JxxtqNH+Pc4iyK+z4a9bHaogEw88Tunx3uLjcks4nft2KDczVArjDh7HtfkuCGC+Bq3+JSRMcikE2euKdO2ioWYRfw4WWp7XBOQkTBBPBqNJVdbmAnibBCzYgZQJp44UydVzULMIL7ryhBC3zeW4rYHG0WmL/DCTBBnK0JhY7j47MQTZz7MNutECXY4gzibj/F0ZJ03qBVOfCMuU2jDD0EnXmdD7lNRL0ImnjgHxhuBPTYT73Gl0gIPJ60VTtxlf7FJjp6sE+cQM8I4SCadeGGfTe0VzgdMRDNx+WEwYfCqmsPKhBM/YH8tMEIwdKMT52q8TC8Imkw8cRH3ePCxfjAT70d0SknOUsmkVlLinDBcmHXij3763TwpgviQwzMCeSbi3DwDxoKROLZPuPdEOkGCOG+7VcYWok6cjbf42IaQOHa4rYi1bVE6WruthYrNkSzxqmzqgjifkfgCm9Vp+PTBpFYAce5igVC6Rrx3X8gKQypCx8c/Wpv09I5EWdtGNBMHi2BJsjMS72PEPHBCqRVOPN7m5C5WW76STvz414mrMuwq8OdC77rpauYp4sINepcoCCNx1k4p7V3dNfRWEI+bW0ILc048/hevl1iIJuILvApIYP+k1AoiLhZmaOD8MfG2i2XytEocvjuIrS4T8b9UWnyPWd9DUoijhVknvl/IiPuqIlyqlboiQ9b+cxErZ7++hkUzH54mLiZiHE06NhDnHKEtLFZIvb+YOF+Y/Xuh1h+fwVaZZHs8JV5n/4xNbQNx3tsNlMS+hrauVhTiwowUxXTiwmL//yPu3PG9Xd7xe5q4cFX2oYiFQyupEBcLs99KGsFv3OebIr/kAb0O4ty7EXG+BzIq2GuT6zQFQCUuFma+vPQ14nwxKOlnOEh5TcS50y4m4iNJ3HgcSn8BjfiKVPgsioIrcAuIjs/o8qqI86nNJyId+eb61lelQFkrGnGxMLNo/LJGvM7bVTb+TPK6iIvJVjdsYQq76LGPhet27XyhTryeTPJtjbjY5jRtUivyuogLezveiNOI876+U00K4cOT508Qca5NmJ/Dzrko5bkiH1KtvDLiLW4h1unTP48++e3zSX6vDARBnA+Nu8uRqTvLVVI1kfLKiCdHKVZKOnFuU5d0k3GpSiAgiCfR9PjQBhK+0ekOtQv02ojzXeaDOtu4UYnzbXlfV7atd9LwS4UiztV1aaFOEBcnhMgrFaq8OuIr/NjDGjHHH31D9OOBcBlJ4gt8J7r+jnjje26uUNGsFSXW/+qIC+eHsFVaVdPqxv1J5RA6STx2N6k3rptOei6VfEz39RFf425QQSPO3aM2FaPjhx8UtUITF8ckyDfeFqeZHxXFslwq+Bvooa+PuNiA04lz94c+qMYPVODYCk08uUBEvfEmz2ofw5NZaw98iKqw3MTvLOvEWz5FnO8PG0xmzhGrFQNxxzUSd/bFaLiF7TWx2730IG4CHSBNLnaW+8uEWNldHgFxoZdV4twGLNFTa9fV1IqJ+ErJSDy5CFSolg7KG+5BuSpuXlXx0imCO35bl+rEEheGg0KcO+IbelkufHa6MMVEXLRjeOM7F9/m5G+xT91KIWXIg4t/KCMhzo9RYeKtg6zn8AB3Cc5FI3G+MJta2n0oYeZtd/gbtLaIl8rl8ueniUelygeKubv7nyiRjB+xi9z4lvj2xyjlPyYLYYG19BkGANZYyn+ptvufyxm3xHf7rhvfnvV91+1Tt8TLBinZOSXEt1WfjrpRxXrGLVmRAzvQyt6+1XZ3n2o745cQVvoPkRZ3N/b7KxTCnrqnPIbd5VxyySWXXHLJJRcr8j9QS547eKFeaQAAAABJRU5ErkJggg==)
* BlockTribune (https://race-coin.io/wp-content/uploads/2018/11/BlockTribune.jpg)
* USA Today (https://www.poorpeoplescampaign.org/wp-content/uploads/2018/02/usatoday.jpg)
* MarketWatch (https://lh3.googleusercontent.com/6zHM9NclkCDg9yHCCBAlQ40qXCoOOPYSon9REyTPbMiLtRy_kV-EVqAjUSpDhQM8Zkg)
* Ask (https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Ask.com_Logo.svg/1200px-Ask.com_Logo.svg.png)
* Entrepreneur (https://assets.entrepreneur.com/static/20160721060814-ENT-logo-white.svg)
* TechStartups (https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsbENADmYL6u202pWUfTDyS2He5sX7dfvyawGgCm9_cn9ngYPL)

---

As for the order of logo importance, I'd probably go something like this: 

1- Entrepreneur
2- Business Insider
3- International Business Times
4- MarketWatch
5- HackerNoon
6- Yahoo! Finance
7- The Merkle
8- USA Today
9- TechStartups
10- Ask
11- ...and then the rest

**Comment by AllienWorks** [comment]
I decided to go with just ~10 of them, since it would be super crowded if we added all of them.

And since I'm linking all logos to the articles, I found out that I can't find Particl articles on these sites:

- https://www.businessinsider.com
- https://www.ibtimes.com
- https://www.marketwatch.com
- https://usatoday.com
- https://ask.com

Do you have the links for them?

---

So just for info, currently we're at this:

![Screenshot from 2019-10-07 18-28-01](https://user-images.githubusercontent.com/1965795/66330248-46f9f880-e930-11e9-8c20-51b4255b7d9f.png)
